### ISSUE TITLE
Export of result table does not work

### ISSUE THREAD

**Issue by oleg-koval** [mechatroner/mechatroner.github.io#2]
After querying CSV export does not work:

```
index.js?version=30:371 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at save_result_table (index.js:371:36)
    at HTMLButtonElement.<anonymous> (index.js:71:25)
save_result_table @ index.js?version=30:371
(anonymous) @ index.js?version=30:71
```

**Comment by mechatroner** [comment]
Thank you for reporting! 
Fixed.
